### PR TITLE
Write qc file

### PR DESCRIPTION
**Pull request by Yu-AnChen**
This PR is focused on
- Parse pixel size metadata, which can be overwritten by manual input, and write it to the output ome-tiff
- Write QC files, currently 3 channels - mask inner outline, contour probability map, and intensity rescaled DNA channel image
- Update dependencies (in dockerfile)

### CODE REVIEW

**Comment by clarenceyapp** [comment]
I suggest switching the mask outlines to `outer` instead of `inner` to be consistent with existing qc files. It's not just more aesthetic looking and easier to interpret, it also matches what is being used in Minerva Analysis.

**Comment by Yu-AnChen** [comment]
Thanks for pointing this out! I took a second look at minerva analysis (https://github.com/labsyspharm/minerva_analysis/wiki/Gating), it looked to me that it was also using inner outline, check out this image, and note the separation between each outlines (I wasn't able to find it in the code, tho)




I think the inner outline is a better choice for tasks like re-coloring them based on continuous and discrete features of the objects. Here are visual references for us to compare (blue: binarized labeled mask; green: outlines using the three methods)

 outline-compare

outline-compare-2

**Comment by clarenceyapp** [comment]
The outlines from s3seg used to be inner a long time ago but the feedback from users was that it was hard to interpret segmentation accuracy because it appears that there are extra objects which are mistaken for over segmentation, so I switched it to outer for them. Regarding Minerva analysis, that is interesting because I watched the Minerva team change it from inner to outer in realtime. 👀

**Comment by Yu-AnChen** [comment]
Do you happen to know where that piece of code in Minerva analysis is? I'm interested to know how the coloring was done for outer outlines. And if Minerva uses the QC outline file generated by s3seg or it uses the mask file then generates outlines.

**Comment by Yu-AnChen** [comment]
Cool I just change to `outer` for generating the outline. Although I think using `inner` is simpler to explain and gives a more useful output for tasks such as pseudo-color the outline based on the feature of the mask object.

**Comment by clarenceyapp** [comment]
Thanks, we could have it user selectable if you thought that's appropriate. The inner files could be written to a non-qc folder for pseudo color since its purpose seems more downstream visualization instead of segmentation quality control.

**Comment by Yu-AnChen** [comment]
Thanks! I think we can do that when it's needed. For now it probably doesn't make sense using extra disk space 🙂

**Pull request merged**
